ALTER TABLE users ADD provider VARCHAR(10);
ALTER TABLE file_references ADD file_url VARCHAR(200);

ALTER TABLE users ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE users ALTER COLUMN role DROP NOT NULL;
ALTER TABLE users ALTER COLUMN status DROP NOT NULL;
ALTER TABLE users ALTER COLUMN sex DROP NOT NULL;
ALTER TABLE users ALTER COLUMN created_date DROP NOT NULL;
ALTER TABLE users ALTER COLUMN updated_date DROP NOT NULL;
ALTER TABLE users ADD CONSTRAINT file_ref_fl FOREIGN KEY (avatar_id) REFERENCES file_references (id);